export global Keyboard {
    callback send(int, [int]);
}

component Button inherits Image {
    min-width: 80px;
    min-height: 80px;
    in property <image> icon;
    in property <int> modifier;
    in property <[int]> keycodes; // https://usb.org/sites/default/files/hut1_3_0.pdf
    Rectangle {
        border-width: 2px;
        border-color: black;
    }
    source: root.icon;
    TouchArea {
        clicked => { Keyboard.send(root.modifier, root.keycodes); }
    }
}

export component App inherits Window {
    width: 320px;
    height: 240px;
    background: white;

    GridLayout {
        Row {
            Button {
                icon: @image-url("images/task-jp.png");
                modifier: 8; // Meta(0x08)
                keycodes: [58, 0, 0, 0, 0, 0]; // F1
            }
            Button {
                icon: @image-url("images/signalslot.png");
                modifier: 8; // Meta(0x08)
                keycodes: [61, 0, 0, 0, 0, 0]; // F4
            }
            Button {
                icon: @image-url("images/windows.png");
                modifier: 8; // Meta(0x08)
                keycodes: [62, 0, 0, 0, 0, 0]; // F5
            }
            Button {
                icon: @image-url("images/slint.png");
                modifier: 8; // Meta(0x08)
                keycodes: [63, 0, 0, 0, 0, 0]; // F6
            }
        }
        Row {
            Button {
            }
            Button {

            }
            Button {

            }
            Button {

            }
        }
        Row {
            Button {

            }
            Button {

            }
            Button {

            }
            Button {

            }
        }
    }
}